MusicApplication/MusicApplication/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('',include('music.urls'))
]

urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MusicApplication/home/urls.py
from django.contrib import admin
from django.urls import path
from .views import home, login_view, logout_view

app_name = 'home'
urlpatterns = [
    path('', home, name = 'home'),
    path("login/",login_view, name="login_view"),
    path('logout/', logout_view, name = 'logout')
    
]

MusicApplication/music/urls.py
from django.contrib import admin
from django.urls import path
from .views import artist_view, artist_info, genre_view, genre_info, album_view, search, track_view,artist_follow

app_name = 'music'
urlpatterns = [
    path('nghe-si/',artist_view, name = 'artist'),
    path('nghe-si/<slug:slug>',artist_info, name = 'artist_info'),
    path('nghe-si/<slug:slug>/follow',artist_follow, name = 'artist_follow'),
    path('the-loai/', genre_view,name='genre'),
    path('the-loai/<slug:slug>',genre_info,name='genre_info'),
    path('album/<slug:slug>',album_view,name='album'),
    path('tim-kiem/',search,name='search'),
    path('bai-hat/<slug:slug>',track_view,name='track'),
    
]

MusicApplication/home/models.py
from django.db import models
# Create your models here.

MusicApplication/home/forms.py
from typing import Any
from django import forms
from django.contrib.auth.models import User

class LoginForm(forms.ModelForm):
    username = forms.CharField(required=True)
    password = forms.CharField(required=True)

class RegisterForm(forms.Form):
    password = forms.CharField(label='Password',\
        widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password',\
        widget=forms.PasswordInput)
    
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']
        
    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for i in self.fields:
            self.fields[i].widget.attrs.update({
                    'class': 'form form-control'
                })
        self.fields['first_name'].label = 'HỌ'
        self.fields['last_name'].label = 'TÊN'
        self.fields['email'].label = 'EMAIL'  
    

    
        

MusicApplication/home/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from music import models
from music.models import Track, Album, Artist, Genre
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q

# Create your views here.
def base(request):
    models.set_trend_track()
    keyword = request.GET.get('keywordInput')
    # đăng nhập
    context = {
        'keywordInput': keyword if keyword else ""
    } 
    return render(request, 'home/base.html', context=context)

def login_view(request):
    error = None
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(username=username, password= password)
        if user:
            login(request, user)
            return redirect('home:home')
        else:
            error='Invalid username or password.'
    context = {
        "error": error
    }
    return render(request, 'home/login.html',context=context)
    
def logout_view(request):
    logout(request)
    return redirect('home:home')

def home(request):
    tracks = Track.objects.all().order_by('-streams')
    albums = Album.objects.all()
    
    # top 10
    if Track.objects.all().__len__()<10:
        tracks = Track.objects.all().order_by('-streams')
    else:
        tracks = Track.objects.all().order_by('-streams')[:10]
    
    tracks2 = None
    if Track.objects.all().__len__()<100:
        tracks2 = Track.objects.all().order_by('-streams')      
    else:
        tracks2 = Track.objects.all().order_by('-streams')[:100]
    
    
    context = {
        'genres': Genre.objects.all(),
        'tracks': tracks,
        'tracks2': tracks2,
        'albums': albums,
        
    }
    return render(request, 'home/index.html', context=context)
'''
def search(request, keyword):
    keywordInput = request.GET.get(keyword) 
    tracks = Track.objects.filter(Q(name__contains=keywordInput)|Q(artists__name__contains=keywordInput)).values().order_by('-created_at')
    albums = Album.objects.filter(Q(name__contains=keywordInput)).values().order_by('-created_at')
    artists = Artist.objects.filter(Q(name__contains=keywordInput)).values().order_by('-created_at')
    context = {
        'tracks': tracks,
        'albums': albums,
        'artists': artists,
    }
    return (request, 'home/search.html', context)
'''

def top_100_view(request):
    
    return redirect('home:home')
    
    

MusicApplication/home/templates/home/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="icon"  href="https://png.pngtree.com/png-vector/20190411/ourmid/pngtree-vector-play-icon-png-image_924817.jpg"  type="image/x-icon">
  <title>Trang nghe nhạc trực tuyến</title>
  <link rel="stylesheet" href="{% static 'style.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous">
  </script>
  
</head>

<body style="background-color: rgb(51, 25, 74);">
  <div>
    <!-- Menu -->
    <nav class="navbar navbar-expand-lg bg-body-tertiary " id="nav" data-bs-theme="dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home:home' %}">Trang nghe nhạc trực tuyến</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link " aria-current="page" href="{% url 'home:home' %}">Trang chủ</a>
            </li>
            <li class="nav-item">
              <a class="nav-link " href="{% url 'music:genre' %}">Thể loại</a>
            </li>
            <li class="nav-item">
              <a class="nav-link " href="{% url 'music:artist' %}">Nghệ sĩ</a>
            </li>
            <li class="nav-item">
              {% if request.user.username %}
                <a class="nav-link " href="{% url 'home:logout' %}">Đăng Xuất</a>
              {% else %}                
                <button type="button" class="nav-link" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
                    Đăng Nhập
                </button>
                <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                  <div class="modal-dialog">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h1 class="modal-title fs-5" id="staticBackdropLabel">Đăng Nhập</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                      </div>
                      <div class="modal-body">
                        {% include "home/login.html" %}
                        
                      </div>
                      <div class="modal-footer">
                          <button type="button" class="btn btn-secondary button" data-bs-dismiss="modal">Close</button>

                      </div>
                      
                  </div>
                </div>
                </div>
              {% endif %}
            </li>
          </ul>
          <form action="{% url 'music:search' %}" method="get">
            {% csrf_token %}
            <div class="d-flex">
                <div class="p-2">
                    <input class="form-control me-2" type="text" id="keywordInput" name="keywordInput" placeholder="Search" value="{{keywordInput}}"/>
                </div>
                <button type="submit" class="btn btn-outline-success">Tìm kiếm</button>
            </div>
        </form>
        </div>
      </div>
    </nav>
    <!-- content -->
    <div class="row">

      <div class="col-12 col-lg-9">
        {% block content %}{% endblock content %}
      </div>
      <div class="col-12 col-lg-3">
        
        {% block content2 %}
        {% endblock %}
      </div>
    </div>
    

  </div>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
    integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous">
  </script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
    integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous">
  </script>
  <style>
      div#nav{
        color: black;
        background-color: black;
      }
      h1{
        color: white
      }
      h2{
        color: white
      }
      h3{
        color: white
      }
      h4{
        color: white
      }
      h5{
        color: white
      }
      a{
        color: white
      }
      td{
        color: white
      }
      p{
        color: white
      }
      span{
        color: white;
      }
      label{
        color: white
      }
  </style>
  <script>
    var buttons = document.getElementsByClassName('btn-play');
    for(var i=0;i<=buttons.length;i++){
      buttons[i].addEventListener('click',function(){
        
      })
    }
  </script>
</body>

</html>

MusicApplication/home/templates/home/index.html
{% extends "home/base.html" %}
{%block content %}
<h2>Bài hát</h2>
<table class="table table-striped">
    <thead>
    <th>#</th>
    <th>Tên</th>
    <th>Lượt theo dõi</th>
    </thead>
    <tbody>
    {% for track in tracks2 %}
        <tr>
        <td><a href="{% url 'music:track' track.slug %}"><img src="{{track.image.url}}" alt="" style="width: 1rem; height: 1rem;"></a></td>
        <td>{{track.name}}</td>
        <td>{{track.streams}}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
<div class="col-12">
    <h2>Album hot nhất hiện nay</h2>
    <div class="row">
        {% for album in albums %}
            <div class="col-3 p-2 text-center">
                <div class="row">
                    <a href="{% url 'music:album' album.slug %}">
                        <img src="{{album.image.url}}" alt="" style="height: 10rem;width: 10rem;">
                    </a>
                    <p class="fs-5">{{album.name}}</p>
                </div>
            </div>
        {% endfor %}
    </div>
</div>



{% endblock %}
{% block content2 %}
<h2>BXH Bài hát</h2>
<table class="table table-striped">
    <thead>
    <th>#</th>
    <th>Tên</th>
    <th>Lượt theo dõi</th>
    </thead>
    <tbody>
    {% for track in tracks %}
        <tr>
        <td><a class="btn btn-success btn-play" href="{% url 'music:track' track.slug %}"><i class="fa fa-play"></i></a></td>
        <td>{{track.name}}</td>
        <td>{{track.streams}}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock content2 %}

MusicApplication/home/templates/home/login.html
<nav>
  <div class="nav nav-tabs" id="nav-tab" role="tablist">
    <button class="nav-link active" id="nav-home-tab" data-bs-toggle="tab" data-bs-target="#nav-login" type="button" role="tab" aria-controls="nav-login" aria-selected="true">Đăng Nhập</button>
    <button class="nav-link" id="nav-profile-tab" data-bs-toggle="tab" data-bs-target="#nav-register" type="button" role="tab" aria-controls="nav-register" aria-selected="false">Đăng ký</button>
  </div>
</nav>
<div class="tab-content" id="nav-tabContent">
  <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-login-tab" tabindex="0">
    <div class="wrapper">
      <form method="post" action="{% url 'home:login_view' %}">
          {% csrf_token %}
          <div class="input-group">
            <label for="username">Username</label>
            <input placeholder="Nhập username" type="text" class="" name="username" required><br>
          </div>
          <div class="input-group">
            <label for="password">Password</label>
            <input placeholder="Nhập password" type="password" class="" name="password" required><br>
          </div>
          <div class="">
              <input type="submit" class="btn btn-primary button" value="Đăng Nhập">
              <a class="btn btn-info button"  href="">Đăng ký</a>
            </div>
      </form>
    </div>
    {% if error %}
        <p>{{ error }}</p>
    {% endif %}
  </div>
  <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-register-tab" tabindex="0">
    <div class="wrapper">
      <form method="post" action="{% url 'home:login_view' %}">
          {% csrf_token %}
          <div class="input-group">
            <label for="username">Username</label>
            <input placeholder="Nhập username" type="text" class="" name="username" required><br>
          </div>
          <div class="input-group">
            <label for="password">Password</label>
            <input placeholder="Nhập password" type="password" class="" name="password" required><br>
          </div>
          <div class="">
              <input type="submit" class="btn btn-primary button" value="Đăng Nhập">
              <a class="btn btn-info button"  href="">Đăng ký</a>
            </div>
      </form>
    </div>
  </div>
</div>

<style>
  .wrapper{
    position: relative;
    justify-content: center;
    padding: 10px;
    border-radius: 5%;
    
  }
  .input-group{
    position: relative;
    margin: 30px 0;
    border-bottom: 2px solid black;

  }
  .input-group label{
    position: absolute;
    top: 50%;
    left: 0.0001rem;
    transform: translateY(-160%);
    pointer-events: none;
    text-decoration: none;
    text-wrap: wrap;
  }
  .input-group input{
    width: 340px;
    height: 40px;
    font-size: 16px;
    background: transparent;
    background-color: none;
    border: none;
    outline: none;
  }
  .button{
    
  }
</style>

MusicApplication/home/templates/home/search.html
{% extends "home/base.html" %}
{% block content %}

{% endblock content %}