MusicApplication/MusicApplication/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('',include('music.urls'))
]

urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MusicApplication/home/urls.py
from django.contrib import admin
from django.urls import path
from .views import home, login_view, logout_view

app_name = 'home'
urlpatterns = [
    path('', home, name = 'home'),
    path("login/",login_view, name="login_view"),
    path('logout/', logout_view, name = 'logout')
    
]

MusicApplication/music/urls.py
from django.contrib import admin
from django.urls import path
from .views import artist_view, artist_info, genre_view, genre_info, album_view, search, track_view,artist_follow

app_name = 'music'
urlpatterns = [
    path('nghe-si/',artist_view, name = 'artist'),
    path('nghe-si/<slug:slug>',artist_info, name = 'artist_info'),
    path('nghe-si/<slug:slug>/follow',artist_follow, name = 'artist_follow'),
    path('the-loai/', genre_view,name='genre'),
    path('the-loai/<slug:slug>',genre_info,name='genre_info'),
    path('album/<slug:slug>',album_view,name='album'),
    path('tim-kiem/',search,name='search'),
    path('bai-hat/<slug:slug>',track_view,name='track'),
    
]

MusicApplication/music/models.py
from typing import Any
from django.db import models
from django.utils import timezone 
from django.contrib.auth.models import User

# Create your models here.

def upload_to(instance, filename):
    return f'static/{instance.name}/{filename}'

class Area(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='khu-vuc/', default='khu-vuc/music_disc.jpg')
    
    def __str__(self):
        return self.name

    class Meta:
        db_table = 'area'
        managed = True
        verbose_name = 'Area'
        verbose_name_plural = 'Areas'

class Genre(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='the-loai/', default='the-loai/music_disc.jpg')
    area = models.ForeignKey(Area, on_delete=models.CASCADE)
    description = models.TextField(null=True)
    slug = models.SlugField(null=True, unique=True)
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
    
    class Meta:
        db_table = 'genre'
        managed = True
        verbose_name = 'Genre'
        verbose_name_plural = 'Genres'
        
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("model_detail", kwargs={"pk": self.pk})

class Artist(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(null=True)
    image = models.ImageField(upload_to='nghe-si/', default='nghe-si/music_disc.jpg')
    area = models.ForeignKey(Area, on_delete=models.CASCADE, null=True)    
    follows = models.IntegerField(default=0)
    created_at = models.DateField(auto_now_add=True)
    slug = models.SlugField(unique=True, null=True)

    def __str__(self):
        return self.name

    def follow(self, state:bool):
        if state:
            self.follows-=1
        else:
            self.follows+=1
        self.save()
        
    class Meta:
        db_table = 'artist'
        managed = True
        verbose_name = 'Artist'
        verbose_name_plural = 'Artists'

class UserArtist(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
    is_follow = models.BooleanField(default=False)
    
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
    
    def follow(self):
        if self.is_follow == True:
            self.is_follow = False
        else:
            self.is_follow = True
        
    class Meta:
        db_table = 'user_artist'
        managed = True
        verbose_name = 'UserArtist'
        verbose_name_plural = 'UserArtists'

        


class Lyric(models.Model):
    name = models.CharField(max_length=100,null=True)
    content = models.TextField()    

    def __str__(self):
        return str(self.name)

    class Meta:
        db_table = 'lyric'
        managed = True
        verbose_name = 'Lyric'
        verbose_name_plural = 'Lyrics'

class Track(models.Model):
    name = models.CharField(max_length=100)
    genres = models.ManyToManyField(Genre)
    artists = models.ManyToManyField(Artist)
    lyrics = models.ManyToManyField(Lyric, null=True)
    file = models.URLField(max_length=200, default='https://www.youtube.com/watch?v=Ora2P-xjPgA')
    image = models.ImageField(upload_to='bai-hat/',default='bai-hat/music_disc.jpg')
    favorites = models.IntegerField(default=0)
    streams = models.IntegerField(default=0)
    top_trend = models.IntegerField(default=-1)
    is_trend = models.BooleanField(default=False)
    created_at = models.DateField(auto_now_add=True)
    slug = models.SlugField(null=True, unique=True)
    
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
    
    def increase_stream(self):
        self.streams+=1
        self.save()
    
    def set_trend(self):
        if self.is_trend:
            self.is_trend=False
        else:
            self.is_trend=True
        self.save()
    
    def set_top(self,top: int):
        self.top_trend = top
    
    class Meta:
        db_table = 'track'
        verbose_name = "Track"
        verbose_name_plural = "Tracks"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("Track_detail", kwargs={"pk": self.pk})
'''
class Trend(models.Model):
    top = models.BigIntegerField(primary_key=True,auto_created=True)
    track = models.ForeignKey(Track, on_delete=models.CASCADE)
    
    class Meta:
        db_table = 'trend'
        managed = True
        verbose_name = 'Trend'
        verbose_name_plural = 'Trends'
'''

class Album(models.Model):
    name = models.CharField(max_length=100)
    tracks = models.ManyToManyField(Track)
    artists = models.ManyToManyField(Artist, null= True)
    image = models.ImageField(upload_to='album/', default='album/music_disc.jpg')
    favorites = models.IntegerField(default=0)
    streams = models.IntegerField(default=0)
    created_at = models.DateField(auto_now_add=True)
    slug = models.SlugField(unique=True, null=True)
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
    
    def increase_stream(self):
        self.streams+=1
        self.save()
        
    def __str__(self) -> str:
        return self.name
            
    class Meta:
        db_table = 'album'
        verbose_name = "Album"
        verbose_name_plural = "Albums"

def set_trend_track():
    track = Track.objects.all().order_by('-streams')
    top = 100
    if track.__len__()>top:
        for i in range(len(track)):
            if i<100 :
                if not track[i].is_trend:
                    track[i].set_trend()
            else:
                if track[i].is_trend:
                    track[i].set_trend()
            track[i].set_top(i+1)
    else:
        for i in range(track.__len__()):
            if not track[i].is_trend:
                track[i].set_trend()
            track[i].set_top(i)
                
    

MusicApplication/music/views.py
from django.shortcuts import render, redirect
from .models import Track, Album, Artist, Genre, Area, Lyric, UserArtist
from django.shortcuts import get_object_or_404
from django.conf import settings
from slugify import slugify
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

# Create your views here.
def genre_view(request):
    # album  
    album = Album.objects.all()
    album_vn = Album.objects.filter(tracks__genres__area__name = 'Việt Nam').distinct()
    album_hanquoc= Album.objects.filter(tracks__genres__area__name= 'Hàn Quốc').distinct()
    album_usuk= Album.objects.filter(tracks__genres__area__name= 'Âu Mỹ').distinct()
    
    # track
    if Track.objects.all().__len__()<10:
        tracks = Track.objects.all().order_by('streams')
    else:
        tracks = Track.objects.all().order_by('streams')[:10]
    # Tất cả thể loại việt nam
    genres_vn = Genre.objects.filter(area__name='Việt Nam').distinct()
    # Tất cả thể loại Hàn Quốc
    genres_hq = Genre.objects.filter(area__name='Hàn Quốc').distinct()
    # Tất cả thể loại Âu Mỹ
    genres_usuk = Genre.objects.filter(area__name='Âu Mỹ').distinct()
    
    
    context = {
        'area': Area.objects.all(),
        'genres': Genre.objects.all(),
        'genres_vn': genres_vn,
        'genres_hq': genres_hq,
        'genres_usuk': genres_usuk,
        'albums': album,
        'tracks': tracks,
        'vn': album_vn,
        'hq': album_hanquoc,
        'usuk': album_usuk,
        
    }
    return render(request, 'music/genre.html', context=context)

def genre_info(request, slug):
    genre = Genre.objects.filter(slug=slug)[0]
    tracks = Track.objects.filter(genres__slug = slug).order_by('-created_at')
    albums = Album.objects.filter(tracks__genres__slug = slug).distinct()
    print(tracks)
    context ={
        'genre': genre,
        'tracks': tracks,
        'albums': albums
    }
    return render(request, 'music/genre_info.html', context=context)


def artist_view(request):
    page = request.GET.get('page')
    limit = request.GET.get("limit")
    
    if not limit or not limit.isnumeric():
        limit = settings.LIMIT_DEFAULT
    
    keyword = request.GET.get('keywordInput')
    if keyword:
        artists = Artist.objects.filter(name__contains = keyword).values().order_by("-created_at")
    else:
        artists = Artist.objects.all().order_by("-created_at")
    
    artists_paginator = Paginator(artists,limit)
    try:
        artists_paginator = artists_paginator.page(page)
    except PageNotAnInteger:
        artists_paginator = artists_paginator.page(1)
    except EmptyPage:
        artists_paginator = artists_paginator.page(artists_paginator.num_pages)
    
    
    context = {
        'artists': artists_paginator,
        "keywordInput": keyword if keyword else "",
        "key": keyword if keyword else ""
    }
    return render(request, 'music/artist.html', context=context)

def artist_info(request, slug):
    artist = Artist.objects.filter(slug=slug)[0]
    tracks = Track.objects.filter(artists__slug = slug)
        
    albums = Album.objects.filter(artists__slug = slug)
    userartist = None
    try:
        userartist = UserArtist.objects.get(user = request.user, artist = artist)
    except UserArtist.DoesNotExist:
        UserArtist.objects.create(user = request.user, artist=artist)
        userartist = UserArtist.objects.get(user = request.user, artist = artist)
        
    context = {
        'artist': artist,
        'tracks': tracks,
        'albums': albums,
        'userartist': userartist
    }
    return render(request, 'music/artist_info.html', context)

def album_view(request,slug):
    album= Album.objects.filter(slug=slug)
    tracks = Track.objects.filter(slug__in = album.values_list('tracks__slug',flat=True))
    artists = Artist.objects.filter(slug__in = album.values_list('artists__slug',flat=True))
    context={
        'album':album[0],
        'tracks':tracks,
        'artists': artists
    }
    return render(request, 'music/album.html', context)

def track_view(request, slug):
    track = Track.objects.filter(slug=slug)
    lyric = Lyric.objects.filter(name__in = track.values_list('lyrics__name'))
    track[0].increase_stream()
    context = {
        'track': track[0]
    }
    return render(request, 'music/track.html', context)

def search(request):
    track = Track.objects.all()
    album = None
    artist = None
    page = request.GET.get("page")
    limit = request.GET.get("limit")
    keyword = request.GET.get('keywordInput')
    
    if not limit or not limit.isnumeric():
        limit = settings.LIMIT_DEFAULT
    if keyword:
        track = Track.objects.filter(name__contains = keyword).values()
        album = Album.objects.filter(name__contains = keyword).values()
        artist = Artist.objects.filter(name__contains = keyword).values()
    else:
        track = Track.objects.all()
        album = Album.objects.all()
        artist = Artist.objects.all()
        
    track_paginator = Paginator(track, limit)
    album_paginator = Paginator(album, limit)
    artist_paginator = Paginator(artist, limit)
    
    try:
        track_paginator = track_paginator.page(page)
    except PageNotAnInteger:
        track_paginator = track_paginator.page(1)
    except EmptyPage:
        track_paginator = track_paginator.page(track_paginator.num_pages)
    
    try:
        album_paginator = album_paginator.page(page)
    except PageNotAnInteger:
        album_paginator = album_paginator.page(1)
    except EmptyPage:
        album_paginator = album_paginator.page(album_paginator.num_pages)
    try:
        artist_paginator = artist_paginator.page(page)
    except PageNotAnInteger:
        artist_paginator = artist_paginator.page(1)
    except EmptyPage:
        artist_paginator = artist_paginator.page(artist_paginator.num_pages)
    
    context = {
        'tracks': track_paginator,
        'albums': album_paginator,
        'artists': artist_paginator,
        'tracks2': track,
        'albums2': album,
        'artists2': artist,
        "keywordInput": keyword if keyword else "",
    }
    return render(request, 'music/search.html', context)

def artist_follow(request, slug):
    artist = Artist.objects.get(slug=slug)
    user = request.user
    userartist = UserArtist.objects.get(user=user,artist=artist)
    print(userartist.is_follow)
    userartist.follow()
    return redirect('music:artist_info',slug)

MusicApplication/music/templates/music/album.html
{% extends "home/base.html" %}
{% block content %}
{% load static %}
<div class="row">
    <div class="container text-center">
        <img src="{{album.image.url}}" alt="", style="width: 10rem;height:10rem;">
        <h1>{{album.name}}</h1>
        <div class="col">
            {% for artist in artists %}
                <a class="artist fs-4" href="{% url 'music:artist_info' artist.slug %}">{{artist.name}}</a>
            {% endfor %}
        </div>
        <div class="col">
            <a class="btn btn-success"><i class="fa fa-play"></i></a>
            <a class="btn btn-love" style=""><i class="fa fa-heart"></i></a>
        </div>
    </div>
    <div class="">
        <table class="table table-fluid">
            <thead>
                <th>#</th>
                <th>Tên bài hát</th>
            </thead>
            <tbody>
                {% for track in tracks %}
                    <tr>
                        <td>
                            <a class="btn btn-primary" href="{% url 'music:track' track.slug%}"><i class="fa fa-play"></i></a>
                            
                        </td>
                        <td>{{track.name}}</td>
                    </tr>
                  
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<!--

    
-->
<style>
    .artist{
        text-decoration: none;
    }
    .btn-love{
        border-color: black;
        border-radius: 60%;
        background-color: whitesmoke;

    }
    .btn-love:hover{
        border-color: black;
        background-color: whitesmoke;
    }
</style>
{% endblock content %}

MusicApplication/music/templates/music/artist.html
{% extends "home/base.html" %}
{%block content %}

<div class="row ">
    <h1>Trang nghệ sĩ</h1>
    <form action="" method="get">
        {% csrf_token %}
        <div class="d-flex">
            <label class="p-2" for="keywordInput">Tìm kiếm</label>
            <div class="p-2">
                <input type="text" id="keywordInput" name="keywordInput" value="{{keywordInput}}"/>
            </div>
            <button type="submit" class="btn btn-primary p-2">Nhập</button>
        </div>
    </form>
    <div class="col-9">
        <div>
            <h2>Nghệ sĩ</h2>
            <div class="container-fluid">
                <div class="row ">
                    {% for artist in artists %}
                        <div class="col-3">
                            <div class="card-body text-center">
                                <a class="rounded " href="{% url 'music:artist_info' artist.slug %}">
                                    <img src="{{artist.image.url}}" alt="" style="width: 10rem;height: 10rem;" srcset="">
                                </a>
                                <div class="text-center fs-5">
                                    <p>{{artist.name}}</p>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <div class="pagination">
                <span class="step-links">
                    {% if artists.has_previous %}
                        <a href="?page={{ artists.previous_page_number }}">previous</a>
                    {% endif %}
                    <span class="current">
                        Page {{ artists.number }} / {{ artists.paginator.num_pages }}.
                    </span>
                    {% if artists.has_next %}
                        <a href="?page={{ artists.next_page_number }}">next</a>
                    {% endif %}
                </span>
            </div>
        </div>
    </div>

</div>

{% endblock %}

MusicApplication/music/templates/music/artist_info.html
{% extends "home/base.html" %}
{% block content %}
    <div class="container-fluid row">
        <div class="mb-3 col-12">
            <div class="row">
                <div class="col-3">
                    <img src="{{artist.image.url}}" alt="" 
                    style="width: 10rem;
                    height: 10rem;" srcset="">
                </div>
                <div class="col-9">
                    <h1>{{artist.name}}</h1>
                    <p>{{artist.description}}</p>
                </div>
                {% if request.user.username %}                  
                    <div>
                        {% if userartist.is_follow %}
                            <a class="btn btn-secondary" href="{% url 'music:artist_follow' artist.slug %}">
                                <i class="fa fa-user-minus"></i>Unfollow
                            </a>
                        {% else %}
                            <a class="btn btn-primary" href="{% url 'music:artist_follow' artist.slug %}">
                                Follow
                            </a>
                        {% endif %}
                    </div>
                {% endif %}
            </div>
        </div>
        <div class="container-fluid">
            <div class="b-3 fs-2">
                <h2>Album</h2>
            </div>
            <div class="container-fluid">
                <div class="row">
                    {% for album in albums %}
                        <div class="col-3 text-center">
                            <a href="{% url 'music:album' album.slug %}">                                
                                <img src="{{album.image.url}}" style="width: 10rem; height: 10rem;" srcset="">
                            </a>
                            <p class="">{{album.name}}</p>
                        </div>
                      
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <style>
        .trackList{
            padding: 1px;

        }
        .centered {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
          }
        a{
            text-decoration: none;
            color: darkblue;
        }
    </style>
{% endblock content %}

MusicApplication/music/templates/music/genre.html
{% extends "home/base.html" %}
{% block content %}
    <div class="container-fluid">
        <div class="col">        
            <h5>Việt Nam</h5>
            {% for genre in genres_vn %}
                <a class="btn btn-secondary" href="{% url 'music:genre_info' genre.slug %}">{{genre}}</a>
            {% endfor %}
        </div>
        <div class="col">        
            <h5>Hàn Quốc</h5>
            {% for genre in genres_hq %}
                <a class="btn btn-secondary" href="{% url 'music:genre_info' genre.slug %}">{{genre.name}}</a>
            {% endfor %}
        </div>
        <div class="col">        
            <h5>Âu Mỹ</h5>
            {% for genre in genres_usuk %}
                <a class="btn btn-secondary" href="{% url 'music:genre_info' genre.slug %}">{{genre.name}}</a>
            {% endfor %}
        </div>
    </div>
    <div class="col-12">
        <h2>Album hot nhất hiện nay</h2>
        <div class="row">
            {% for album in albums %}
                <div class="col-3 p-2 text-center">
                    <div class="row">
                        <a href="{% url 'music:album' album.slug %}">
                            <img src="{{album.image.url}}" alt="" style="height: 10rem;width: 10rem;">
                        </a>
                        <p class="fs-5">{{album.name}}</p>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    <div class="col-12">
        <h2>Nhạc Hàn Quốc</h2>
        <div class="row">
            {% for album in hq %}
                <div class="col-3 p-2 text-center">
                    <div class="row">
                        <a href="{% url 'music:album' album.slug %}">
                            <img src="{{album.image.url}}" alt="" style="height: 10rem;width: 10rem;">
                        </a>
                        <p class="fs-5">{{album.name}}</p>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    <div class="col-12">
        <h2>Nhạc Âu Mỹ</h2>
        <div class="row">
            {% for album in usuk %}
                <div class="col-3 p-2 text-center">
                    <div class="row">
                        <a href="{% url 'music:album' album.slug %}">
                            <img src="{{album.image.url}}" alt="" style="height: 10rem;width: 10rem;">
                        </a>
                        <p class="fs-5">{{album.name}}</p>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}
{% block content2 %}
<h2>BXH Bài hát</h2>
<table class="table table-striped">
    <thead>
    <th>#</th>
    <th>Tên</th>
    <th>Lượt theo dõi</th>
    </thead>
    <tbody>
    {% for track in tracks %}
        <tr>
        <td><a class="btn btn-success btn-play" href="{% url 'music:track' track.slug %}"><i class="fa fa-play"></i></a></td>
        <td>{{track.name}}</td>
        <td>{{track.streams}}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock content2 %}

MusicApplication/music/templates/music/genre_info.html
{% extends "home/base.html" %}
{% block content %}
    <div class="row">
        <div class="col-3">            
            <img src="{{genre.image.url}}" alt="" style="width: 10rem; height:10rem;">
        </div>
        <div class="col-9">
            <h1>{{genre.name}}</h1>
            <p>
                {{genre.description}}
            </p>
        </div>
    </div>
    <div class="row">
        <h2>Album Nhạc {{genre.name}}</h2>
        <div class="row text-center">
            {% for album in albums %}
                <div class="col-3">                        
                    <a href='{% url "music:album" album.slug %}'>
                        <img src="{{album.image.url}}" alt="" style="width: 10rem; height:10rem;">
                    </a>
                    <h5>{{album.name}}</h5>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock content %}

MusicApplication/music/templates/music/search.html
{% extends "home/base.html" %}
{% block content %}
  
<form action="" method="get">
    {% csrf_token %}
    <div class="d-flex">
        <div class="p-2">
            <input class="form-control me-3" placeholder="Tìm kiếm bài hát khác" type="text" id="keywordInput" name="keywordInput" value="{{keywordInput}}"/>
        </div>
        <button type="submit" class="btn btn-primary p-2">Nhập</button>
    </div>
</form>
<h2>Kết quả tìm kiếm {{keywordInput}}</h2>
<nav>
    <div class="nav nav-tabs" id="nav-tab" role="tablist">
        <button class="nav-link active" id="nav-all-tab" data-bs-toggle="tab" data-bs-target="#nav-all" type="button" role="tab" aria-controls="nav-all" aria-selected="true">Tất cả</button>
        <button class="nav-link" id="nav-track-tab" data-bs-toggle="tab" data-bs-target="#nav-track" type="button" role="tab" aria-controls="nav-track" aria-selected="false">Bài hát</button>
        <button class="nav-link" id="nav-profile-tab" data-bs-toggle="tab" data-bs-target="#nav-profile" type="button" role="tab" aria-controls="nav-profile" aria-selected="false">Album</button>
    </div>
</nav>
  <div class="tab-content" id="nav-tabContent">
    <div class="tab-pane fade show active" id="nav-all" role="tabpanel" aria-labelledby="nav-all-tab">
        <div class="row">
            <h3>Bài hát</h3>
            <div class="col-9">
                <div class="container-fluid">
                    <div class="row ">
                        {% for track in tracks %}
                            <div class="col-3">
                                <div class="card-body text-center">
                                    <a class="rounded " href="{% url 'music:track' track.slug %}">
                                        {% load static %}
                                        <img src="{{track.image.url}}" alt="" style="width: 7rem;height: 7rem;" srcset="">
                                    </a>
                                    <div class="text-center fs-5">
                                        <p>{{track.name}}</p>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            
        </div>
        <div class="row">
            <h3>Album</h3>
            <div class="col-9">
                <div class="container-fluid">
                    <div class="row ">
                        {% for album in albums %}
                            <div class="col-3">
                                <div class="card-body text-center">
                                    <a class="rounded " href="{% url 'music:album' album.slug %}">
                                        <img src="{{album.image.url}}" alt="" style="width: 7rem;height: 7rem;" srcset="">
                                    </a>
                                    <div class="text-center fs-5">
                                        <p>{{album.name}}</p>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="tab-pane fade show active" id="nav-track" role="tabpanel" aria-labelledby="nav-track-tab">
        <div class="row">
            <div class="col-9">
                <div class="container-fluid">
                    <div class="row ">
                        {% for track in tracks2 %}
                            <div class="col-3">
                                <div class="card-body text-center">
                                    <a class="rounded " href="{% url 'music:track' track.slug %}">
                                        {% load static %}
                                        <img src="{{track.image.url}}" alt="" style="width: 7rem;height: 7rem;" srcset="">
                                    </a>
                                    <div class="text-center fs-5">
                                        <p>{{track.name}}</p>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        
    </div>
    <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
        <div class="row">
            <h3>Album</h3>
            <div class="col-9">
                <div class="container-fluid">
                    <div class="row ">
                        {% for album in albums2 %}
                            <div class="col-3">
                                <div class="card-body text-center">
                                    <a class="rounded " href="{% url 'music:album' album.slug %}">
                                        <img src="{{album.image.url}}" alt="" style="width: 7rem;height: 7rem;" srcset="">
                                    </a>
                                    <div class="text-center fs-5">
                                        <p>{{album.name}}</p>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
  </div>



{% endblock content %}

MusicApplication/music/templates/music/track.html
{% extends "home/base.html" %}
{% block content %}
<div class="row">
    <h3>{{track.name}}</h3>
    <iframe scrolling="no" width="300" height="600" src="{{track.file}}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreenframeborder="0" allowfullscreen>
    </iframe>
    <a class="btn btn-primary" href="">thêm vào danh sách chờ</a>
</div>
{% endblock content %}